### ISSUE TITLE
Blender addon throws an ungraceful error with invalid export path

### ISSUE THREAD

**Issue by Lamoot** [bikemurt/blender-godot-pipeline#3]
Greetings!

I recently bought the Blender addon from Blendermarket and the core functionality works great. I've encountered a few smaller bugs that take away from the user experience though and this is one of them.

Since there's no repository for the Blender addon itself, I decided to post the bug report here. Please let me know if you'd prefer another place for this. 

This happened when I initially wrongly copied Godot's local path and not the required full system path. It happens with any invalid path though, Blender throws a huge popup of the error that looks scary to the user.
![invalid_export_path](https://github.com/user-attachments/assets/829cddec-7804-4662-966a-48f2c97e392a)

It'd be a nicer user experience if the addon showed a dedicated notification and state the cause why the export failed.

I'm using Blender 4.2.3 and 2.4 version of the Blender addon.

**Comment by bikemurt** [comment]
No worries! This is exactly the right place for this kind of thing. It will help me track things. When it is fixed, I will close the issue with a comment.

**Comment by Lamoot** [comment]
Sounds good! I'll post any other bugs here as well.

**Comment by bikemurt** [comment]
![image](https://github.com/user-attachments/assets/5ba837c1-d59e-4c76-9719-804c6760dd46)
Patched as version 2.4.1 https://blendermarket.com/products/blender-godot-pipeline-addon

**Comment by bikemurt** [comment]
One more thought - will investigate more if it is a problem, but checking to see if a path is valid is not trivial ([possible on Windows](https://stackoverflow.com/questions/9532499/check-whether-a-path-is-valid-in-python-without-creating-a-file-at-the-paths-ta)) but would break other OS implementations.

**Comment by Lamoot** [comment]
It's much nicer now, works here, thank you for the fix.
