### ISSUE TITLE
Proposal: Clear Addon Data and Display Addon Data to work on MESH and OBJECT properties at the same time

### ISSUE THREAD

**Issue by Lamoot** [bikemurt/blender-godot-pipeline#5]
Hello once again! I've been using the addon pipeline some more in recent days and I'm liking the fast workflow more and more. Doing so I experienced a few corner that could be polished and here's one of them.

![addon_data_utils](https://github.com/user-attachments/assets/d8588921-37d1-4896-bdab-3c066075d485)

**1.)** _Clear Addon Data_ tooltip says "Clear All Customs" but it only clears either custom properties on the MESH or custom properties on the OBJECT. Depending of course on whether _Assign to Mesh_ option is enabled or not. It feels it would make sense that the button erased all custom properties related to the addon.

**2.)** Following the same track of thought I was wondering if it made sense that the _Display Addon Data_ would show all custom properties of an object, whether assigned to OBJECT or MESH data level. The popup panel would then be something like this (quick and unpolished mockup)

![crappy_mockup](https://github.com/user-attachments/assets/644dce8c-9a19-4ad6-81f4-d298b3193150)

**Comment by bikemurt** [comment]
@Lamoot  just to update you, this will be resolved in the latest branch. Updates from #7 will make the UI feedback better overall.

- Clearing all customs removes all object and mesh customs
- Display custom data shows a panel for object customs, and a panel for mesh customs
