### ISSUE TITLE
Proposal: Update Collision Dimensions button

### ISSUE THREAD

**Issue by Lamoot** [bikemurt/blender-godot-pipeline#7]
The proposal is to have a button similar to _Set Collisions_ button, but it would only update collision dimension properties while the collision shape and body type would not change.

![update_dimensions](https://github.com/user-attachments/assets/20ca7800-2b3c-483a-8e13-19da2af721c8)

The problem I have is when building a level, I give objects different collision shapes, _box,_ _cylinder_ etc. and different body types. Then I continue to shape the level and iterate on the meshes. Every time the dimensions change, the collision dimensions need to be updated and this for multiple objects.

I then need to remember what sort of collision shape and body they had in the first place and select those values in the addon's UI and use _Set Collisions_ to assign the new values. While it's doable, it quickly gets in the way of quick iteration and compounds the more objects and the more complex their collision setup is (e.g. multiple collider children per parent mesh).

**Comment by bikemurt** [comment]
Just letting you know I haven't lost track of this one. I think the UI needs an overhaul to make feedback more intuitive.

In an ideal world, when an object is selected in Blender, all of the options in the menu should update with the values contained in that object.

Challenge is twofold: 1) programming this type of feedback using the bpy system is painful, and 2) the addon up to this point has been pretty much backwards compatible with v1.0, so I don't want to change the structure of how the custom data works.

Will update when I have something.

**Comment by bikemurt** [comment]
@Lamoot would this solve the issue? I'm working on incorporating full "feedback" into the addon. Meaning any time you select an object, the addon properties are updated as appropriate. This clip shows three different physics bodies and collision shapes:

https://github.com/user-attachments/assets/1c7bed9b-901b-4804-b119-07f64848b384

My plan is to incorporate this for all addon features.

**Comment by bikemurt** [comment]
@Lamoot  I've added you to the private repo for the Blender python addon. You can see this update here: https://github.com/bikemurt/b2g-python/blob/ui_updates/godot_pipeline_v242_blender42%2B.py

If you want to do any testing that would be great (but obviously not required). I will be merging this in along with some other changes for v2.5 and posting soon.

**Comment by Lamoot** [comment]
Heya, thanks for the update, I've checked it and it's a nice improvement. It already helps when one wants to update a single object and its collisions so you don't have to retrieve the original collision settings. I was thinking of how this could work with multiple objects though.

For example, If I want to update an object with a box shape and an object with a cylinder shape, I'd have to select them separately and _Set Collisions_ for each of them. Otherwise all of the objects will receive the last selected object's collision settings. The workflow idea I had in my mind, and maybe it wasn't properly presented in the original proposal, is:
* select a whole bunch of objects, perhaps even the whole scene
* update the dimensions
* export

With three simple steps, everything is updated and exported and I can check the result in Godot. The goal here is the fastest possible iteration without having to think much about the specific settings of each or any object. Perhaps the need I describe here will reveal itself to not be so big. I'll start using the updated addon and see how it affects the workflow. 

With all that said I'd like to again emphasize how the addon is an immense improvement for the Godot to Blender workflow and how my proposals are in the _finesse_ territory.

**Comment by bikemurt** [comment]
Thanks again for the feedback. It's a value point and I will consider this in future iterations.

At the end of the day, I totally agree- it's about whatever workflow minimizes clicks and makes iteration faster.
