### ISSUE TITLE
Origin Displacement When Using Godot Collision Shapes

### ISSUE THREAD

**Issue by FunkyArmor** [bikemurt/blender-godot-pipeline#9]
Wonderful Addon! I cannot describe to you the speed and time this addon has afforded me! Thank you!

I am experiencing an odd issue in which using a collision shape option instead of Trimesh or Simplemesh, the asset re sets the origin of the object to its center. I understand the requirement on your end for this. Making the collision shapes in Godot I can imagine is much easier with this. However for quick level design I need some of my assets to have origins equal to there lowest most verity. And upon changing the origins after applying the collision shapes, the collision shapes dont appear in Godot correctly. And with how many assets I find myself importing and using, individually correction every collision shape is a tad nuts. But ya just wanted to put this out there and see if someone has already fixed this issue.

<img width="407" alt="image" src="https://github.com/user-attachments/assets/981a0696-1663-4166-bede-780ebdb25de5" />
<img width="393" alt="image" src="https://github.com/user-attachments/assets/26b92af4-181a-4e53-8bb8-918cb2f35dd3" />

-

<img width="466" alt="image" src="https://github.com/user-attachments/assets/fc3b711e-7a6e-43d4-a2f6-0aada0db4021" />
<img width="566" alt="image" src="https://github.com/user-attachments/assets/abd3bd94-1e7b-4315-b168-ec67bde199cd" />

**Comment by bikemurt** [comment]
Thanks for submitting the issue. Many have commented on this over the past year, and it's a surprisingly complicated issue. The reason it is complicated is for maintaining backwards compatibility - I don't want to necessarily break the pipeline for people who have custom properties already set in their models.

I'm working on this today, and I think I've found an approach that will work. I've added an additional checkbox (that will be checked by default in new versions) called "Preserve Origin":
![image](https://github.com/user-attachments/assets/8eb3a2d6-3c95-4bdb-92d2-1d2f985a2d5c)

The general solution will involve:

1. Blender no longer resets the origin to the center of the bounding box
2. Blender will supply the object with the bounding box origin coordinates
3. Godot will recognize the "Preserve Origins" flag, and displace the collision shapes as appropriate

This *may* break compound collision shapes, but I will update as I learn more. I'm hoping to bring this into version 2.5.

**Comment by bikemurt** [comment]
I have rolled out a fix for this. Here the origin is sitting on the bottom of the shape:

![image](https://github.com/user-attachments/assets/76abcee8-8949-4e7c-a707-acec483e6cb1)

![image](https://github.com/user-attachments/assets/96436092-d2cc-4d36-b159-c1307d157500)

I've invited you to the private repo for the blender addon (I'm going to try this workflow going forward). So if you can help me test it, that would be great. Please report back any issues you find here and I can patch things as appropriate:

Godot addon (not pushed to addon store yet):
https://github.com/bikemurt/blender-godot-pipeline/blob/origin_fix/addons/blender_godot_pipeline/SceneInit.gd

Blender python addon branch:
https://github.com/bikemurt/b2g-python/blob/origin_fix/godot_pipeline_v242_blender42%2B.py

**Comment by FunkyArmor** [comment]
Wow!!!!! You work so fast! Thank you so much brother I'll give this a shot in just a bit thank you! This literally will save me uncountable hours!

I'll give it a shot and see how things seem to be working!

**Comment by bikemurt** [comment]
I was able to get compound collisions to work nicely. I think this workflow will be far superior to anything else - we get compound collisions "for free", since the origin point is calculated by the new `center_x/y/z` properties.

Let me know if you have any questions about how it should work or feedback. Otherwise, I will likely merge and publish v2.5 in a couple of days.

**Comment by FunkyArmor** [comment]
This has worked perfectly!! The workflow works soooo well and I was able to successfully import 200 assets correctly in one go, with correct origins and colliders! Thank you so much!
